exclude: ['node_modules','.DS_Store','.git-ignore', '.ruby-version','.git/','Gemfile', 'Gemfile.lock']

collections:
  blog       :
    output    : true
    permalink : /:collection/:path/

production_url : https://sequenceserver.com
